{
    pools {
        ammId
        name
        coin {
            chainId
            address
            name
            decimals
            symbol
            logoURI
        }
        pc {
            chainId
            address
            name
            decimals
            symbol
            logoURI
        }
        lp {
            chainId
            address
            name
            decimals
            symbol
            logoURI
        }
        stats {
            tvl_pc
            tvl_coin
            price
            vol24h
        }
    }
}